name: lint_test_build
on: push
jobs:
    workflow-jobs:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: Installing dependencies
              run: npm install
            - name: test
              run: npm run-script test
            - name: build
              run: npm run-script build
            - name: lint
              run: npm run-script lint
            - name: finishing up
              run: echo "All ok. Done" 

